name: Python application CI

on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        id: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up uv
        uses: astral-sh/setup-uv@v1
        with:
          # Use the Python executable path from the setup-python step's output
          python-version: ${{ steps.setup_python.outputs.python-path }} # <-- CRITICAL CHANGE HERE

      - name: Install dependencies and run tests
        run: |
          uv venv
          source .venv/bin/activate
          uv pip install pytest
          pytest -v tests/ --junitxml=test-results-${{ matrix.python-version }}.xml

      - name: Upload pytest test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results-${{ matrix.python-version }}
          path: test-results-${{ matrix.python-version }}.xml
